# Generated by Django 2.0.6 on 2018-06-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('level', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='contrib',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Member'),
        ),
    ]
